import type { Metadata } from "next";
import { PrimeReactProvider } from 'primereact/api';
import "primereact/resources/themes/lara-light-cyan/theme.css";
import { Poppins } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import 'primeicons/primeicons.css';
import "./globals.css";
import { ToastContainer } from "react-toastify";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Marini | Página Inicial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body className={inter.className}>
          <ToastContainer />
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
